deployments:
  deploymentGating:
    enabled: true # to enable the feature
    retry: 50 # run poll action 50 times
    sleep: 30 # wait 30 seconds between each poll
    environments: # select the environments you'd like to use with this feature
    - development
    - production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzIwM2VkMWE0LTE0MmEtNDE0Yy1hYjY4LTA1OGMzMDBkODAxMS9lNDUzYzg1NC1lMTMzLTExZWUtYTRiNC0xMjhiNDI4MTk0MjQ=
